#!/bin/bash
# kvmcheck - Utility for verifiyng hardware enablement for KVM
# Copyright (C) 2018 HXR LLC
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

VERSION="0.1"

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -r|--report)
        if [ -z "$2" ]; then
            REPORT=1
        else
            REPORT="$2"
            shift # remember to shift the argument too
        fi
        shift
        ;;
    esac
done
set -- "${POSITIONAL[@]}"

if [[ "$REPORT" -eq 1 || ! -z "$REPORT" ]]; then
    echo "Reporting not implemented yet"
    exit 0
fi

LSCPU="${LSCPU:-$(which lscpu)}"
LSCPU_output="$($LSCPU)"

LSBRELEASE="${LSBRELEASE:-$(which lsb_release)}"
LSBRELEASE_output="$($LSBRELEASE -a)"

declare -a flags
declare -a modules

ok() {
  printf "%s\\n" "$(tput setaf 2)$*$(tput sgr0)"
}
warn() {
  printf "%s\\n" "$(tput setaf 3)$*$(tput sgr0)" >&2
}
error() {
  printf "%s\\n" "$(tput bold; tput setaf 1)$*$(tput sgr0)" >&2
}

split_read() {
    grep '^'"$2"'' <<< "$1" | awk '{for(i='"${3:-2}"'+1;i<=NF;i++) printf("%s%s",$i,i==NF?RS:OFS);}'
    return
}

check_cpu_flag() {
  local flag="$1"
  grep -E -c " $flag " <<<"$LSCPU_output"
  return
}

check_kvm_amd() {
  # Check CPU extensions for Hardware Virtualization support
  # https://en.wikipedia.org/wiki/X86_virtualization#Central_processing_unit
  # Virtualization: AMD-V
  # SVM: Secure Virtual Machine
  flag=("svm;$(check_cpu_flag 'svm')")
  if [[ ${flag##*;} -ne 0 ]]; then
    ok "CPU supports Hardware Virtualization"
  else
    error "Error: Support for 'AMD-V' CPU extension not found - Check specifications"
    exit 1
  fi
  flags+=($flag)
  # Check: KVM kernel module loaded
  module="kvm_amd;$(lsmod | grep -m 1 -e -c '(^kvm_amd)')"
  if [[ ${module##*;} -ne 0 ]]; then
    ok "KVM kernel module loaded"
  else
    error "Error: kvm_amd kernal module not loaded - Check BIOS"
  fi
  modules+=($module)
  if [[ -d "/sys/module/kvm_amd" ]]; then
    # Interrupt Virtualization
    # https://en.wikipedia.org/wiki/APICv#Interrupt_virtualization_(AMD_AVIC_and_Intel_APICv)
    flag="avic;$(cat /sys/module/kvm_amd/parameters/avic)"
    if [[ ${flag##*;} -ne 0 ]]; then
      ok "Interrupt Virtualization enabled"
    else
      error "Error: AMD AVIC not enabled - try: 'modprobe kvm_amd avic=1'"
    fi
    flags+=($flag)
    # Nested Virtualization
    # https://en.wikipedia.org/wiki/Nested_virtualization#Nested_virtualization
    flag="nested;$(cat /sys/module/kvm_amd/parameters/nested)"
    if [[ ${flag##*;} -ne 0 ]]; then
      ok "Nested Virtualization enabled"
    else
      warn "Nested Virtualization disabled"
    fi
    flags+=($flag)
    # Nested Page Tables
    flag="npt;$(cat /sys/module/kvm_amd/parameters/npt)"
    if [[ ${flag##*;} -ne 0 ]]; then
      ok "Nested Virtualization enabled"
    else
      warn "Nested Page Tables disabled"
    fi
    flags+=($flag)
  else
    error "Error: unable to access kernal parameters"
  fi
}

check_kvm_intel() {
  # Check CPU extensions for Hardware Virtualization support
  # https://en.wikipedia.org/wiki/X86_virtualization#Central_processing_unit
  # Virtualization: VT-x
  # VMX: Virtual Machine Extensions
  flag="vmx;$(check_cpu_flag 'vmx')"
  if [[ ${flag##*;} -ne 0 ]]; then
    ok "CPU supports Hardware Virtualization"
  else
    error "Error: Support for 'VT-x' CPU extension not found - Check specifications"
    exit 1
  fi
  flags+=($flag)
  # Check: KVM kernel module loaded
  module="kvm_intel;$(lsmod | grep -m 1 -E -c '(^kvm_intel)')"
  if [[ ${module##*;} -ne 0 ]]; then
    ok "KVM kernel module loaded"
  else
    error "Error: kvm_intel kernel module not loaded - Check BIOS"
  fi
  modules+=($module)
  if [[ -d "/sys/module/kvm_intel" ]]; then
    # Interrupt Virtualization
    # https://en.wikipedia.org/wiki/APICv#Interrupt_virtualization_(AMD_AVIC_and_Intel_APICv)
    flag="apicv;$(grep -c Y /sys/module/kvm_intel/parameters/enable_apicv)"
    if [[ ${flag##*;} -ne 0 ]]; then
      ok "Interrupt Virtualization enabled"
    else
      error "Error: Intel APICv not enabled"
    fi
    flags+=($flag)
    # Nested Virtualization
    # https://en.wikipedia.org/wiki/Nested_virtualization#Nested_virtualization
    flag="nested;$(grep -c Y /sys/module/kvm_intel/parameters/nested)"
    if [[ ${flag##*;} -ne 0 ]]; then
      ok "Nested Virtualization enabled"
    else
      warn "Nested Virtualization disabled"
    fi
    flags+=($flag)
  else
    error "Error: unable to access kernal parameters"
  fi
}

################################

echo "$(tput sgr 0 1)Verifiyng hardware enablement for KVM$(tput sgr0)"

cpu_model=$(split_read "$LSCPU_output" "Model name:")
os=$(split_read "$LSBRELEASE_output" "Description:" 1)

if [[ "$(grep '^Vendor\ ID:' <<<"$LSCPU_output" | grep -c -i 'Intel' )" -ne 0 ]]; then
  cpu_vendor="intel"
elif [[ "$(grep '^Vendor\ ID:' <<<"$LSCPU_output" | grep -c -i 'AMD')" -ne 0 ]]; then
  cpu_vendor="amd"
else
  cpu_vendor="unknown"
fi

case $cpu_vendor in
  intel)    check_kvm_intel;;
  amd)      check_kvm_amd;;
  unknown)  error "Unknown CPU Vendor" && exit 1;;
esac

# Check for 64-bit support
flag="x86_64;$(check_cpu_flag 'lm')"
if [[ ${flag##*;} -ne 0 ]]; then
  ok "64-bit support enabled"
else
  warn "Warning: Enable 64-bit support for improved performance"
fi
flags+=($flag)

# Check: /dev/kvm permissions
if [[ -c "/dev/kvm" ]]; then
  ok "/dev/kvm Found"
else
  error "Error: /dev/kvm Not Found"
fi
if [[ -w "/dev/kvm" ]]; then
  ok "/dev/kvm writeable"
else
  error "Error: /dev/kvm - Check permissions"
fi

# I/O MMU Virtualization
# https://en.wikipedia.org/wiki/X86_virtualization#I/O_MMU_virtualization_(AMD-Vi_and_Intel_VT-d)
module="iommu;$(find /sys 2>&1 /dev/null | grep -m -1 -c dmar)"
if [[ ${module##*;} -ne 0 ]]; then
  ok "I/O MMU Virtualization Enabled"
else
  error "Error: I/O MMU Virtualization not enabled"
fi
modules+=($module)

read -d '' yaml <<- EOF
# kvmcheck v$VERSION
# Run 'kvmcheck --report $file' for more details

- os: $os
  kernel: $(uname -r)
  vendor: $cpu_vendor
  cpu: $cpu_model
  modules:
$(for i in "${modules[@]}"; do printf "%s%s: %s\n" "  - " "${i%%;*}" "${i##*;}"; done)
  flags:
$(for i in "${flags[@]}"; do printf "%s%s: %s\n" "  - " "${i%%;*}" "${i##*;}"; done)
EOF

echo "$yaml"

exit 0
